/* eslint-disable operator-linebreak */

// WEB3 CONTEXT
export const SET_WEB3_PROVIDER = 'SET_WEB3_PROVIDER'
export const SET_ADDRESS = 'SET_ADDRESS'
export const SET_ADDRESS_PROVIDER = 'SET_ADDRESS_PROVIDER'
export const SET_WEB3AUTH_ADDRESS = 'SET_WEB3AUTH_ADDRESS'
export const SET_BIND_ADDRESS = 'SET_BIND_ADDRESS'
export const RESET_WEB3_PROVIDER = 'RESET_WEB3_PROVIDER'
export const CAMPAIGN_LIST = 'CAMPAIGN_LIST'
export const CAMPAIGN_LOADING = 'CAMPAIGN_LOADING'
export const BANNER_LIST = 'BANNER_LIST'
export const BANNER_LOADING = 'BANNER_LOADING'
export const PERK_LIST = 'PERK_LIST'
export const PERK_LOADING = 'PERK_LOADING'
